name = "WindowAbstractions"
uuid = "e18202ca-4a7d-4de8-b056-fa6bbd7de157"
authors = ["Cédric Belmant"]
version = "0.9.0"

[deps]
BitMasks = "a3e06817-fd65-4797-8291-16f435bc2529"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"

[weakdeps]
XKeyboard = "0c8a7d74-93ea-4f23-9ed1-b26578bfdfe6"

[extensions]
WindowAbstractionsXKB = "XKeyboard"

[compat]
BitMasks = "0.1"
DocStringExtensions = "0.8, 0.9"
StructEquality = "2.1.0"
XKeyboard = "0.1.4"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Xorg_libxcb_jll = "c7cfdc94-dc32-55de-ac96-5a1b8d977c5b"

[targets]
test = ["Test", "XKeyboard", "Xorg_libxcb_jll"]
