name = "WindowAbstractions"
uuid = "e18202ca-4a7d-4de8-b056-fa6bbd7de157"
authors = ["Cédric Belmant"]
version = "0.2.3"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
Parameters = "0.12"
DocStringExtensions = "0.8"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
